# Generated by Django 6.0.4 on 2026-04-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('fundacion', 'Fundacion'), ('junta', 'Junta de Vecinos'), ('club', 'Club Deportivo')], max_length=50)),
                ('direccion', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
